### PR TITLE
stage-* presets are Russians dolls

### PR DESCRIPTION
**Pull request by babylon05**
Going out on a limb on this one but from what I understand the Babel stage-* presets are Russians dolls so stage-0 includes all 1, 2 & 3 stage plugins. stage-3 already includes transform-async-to-generator.

### CODE REVIEW

**Comment by thelordoftheboards** [comment]
Thank you for organizing that. When I was converting to Babel 6 I was just in the 'add stuff till it starts working' mode.

**Comment by thelordoftheboards** [comment]
image

**Comment by babylon05** [comment]
Welcome, happy to contribute! This project is exactly what I was looking
for and then some - in awe. Any plans on integrating Passport?

**Comment by thelordoftheboards** [comment]
Absolutely. My plan is to use JWT tokens as they are used now (looking forward to Relay on React Mobile here), and use Passport for anything else.
However, I don't think I will be getting to that soon. If you feel like doing that PRs are of course welcome.
I have been looking at https://auth0.com/ could be very useful for things like active directory.

**Comment by babylon05** [comment]
Great. Looks like OOB Relay React Native is not too far away
<https://github.com/facebook/relay/issues/26>.

Not sure if you've seen:
boilerplate w/ React, Relay, React-Router, SSL, Express and Passport
<https://github.com/MattMcFarland/reactathon>

**Comment by thelordoftheboards** [comment]
#26 has been not too far away for a while ... but I am hoping it will get resolved soon, there is a lot of work that has been done there. In the meantime the isomorphic-relay works fairly well and I am not bothered by it. I am more irked by the fact that the network layer injection is a global, hence the whole queue thing.
Speaking of isomorphism, Material-UI has its own problems with it, not least the agent global.
I like the reactathon. Really cool project.

**Comment by terrisgit** [comment]
I must be missing other changes because I updated just .babelrc and "npm start" hangs.

I also tried "npm run start-dev" and I get

Server request for query `Viewer` failed for the following reasons:

1. Signature verification failed
Error: Server request for query `Viewer` failed for the following reasons:

1. Signature verification failed
    at node_modules/react-relay/lib/RelayDefaultNetworkLayer.js:73:23
    at run (gnode_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:104:47)
    at gnode_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:115:28
    at flush (gnode_modules/babel-polyfill/node_modules/core-js/modules/$.microtask.js:19:5)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickDomainCallback (node.js:422:13)
Timeout for renderer

**Pull request merged**
